spring:
  datasource:
    url: jdbc:mysql://localhost:3306/frame_me_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ME(yyXcSdXTD0x/NVk0pXe41WQLEZBCArW55GdRFxQwRPegpEcWqF507VDzp+FkAi58)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  http:
    serviceclient:
      tester:
        base-url: http://localhost:9090
        read-timeout: 10s
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
      com.zaxxer.hikari: INFO
#mybatis-flex:
#  default-datasource-key: master
#  datasource:
#    master:
#      url: jdbc:mysql://localhost:3306/frame_me_sso?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      type: hikari
#      maximum-pool-size: 10
#      minimum-idle: 5


# redis
# sa-token 基础登录
# auth
# sa-token、cookie 模式
# 多个文件的 pom
# snowflake my-felx
# cache
# notify
# op-audit
# nacos encrypt
# base