<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.frame.me</groupId>
        <artifactId>frame-me-launcher</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>frame-me-sso</artifactId>
    <packaging>pom</packaging>
    <name>frame-me-sso</name>
    <description>SSO 单点登录服务聚合工程（api 契约 + service 启动服务）</description>

    <modules>
        <module>frame-me-sso-api</module>
        <module>frame-me-sso-service</module>
    </modules>
</project>
